### ISSUE TITLE
[FEATURE] CRAN Preparation and Documentation Checklist

### ISSUE THREAD

**Issue by rsh52** [CHOP-CGTDataOps/REDCapTidieR#34]
# Feature Request Description
In preparation of CRAN submission, we must address the following:

- [x] All functions need to have `roxygen2` documentation and appropriate tags
   - [x] Including `@return` and `@example` tags
- [x] Vignette documentation updates (see #18)
   - [x] README updates 
- [x] Update the `DESCRIPTION` file
- [x] Create a NEWS article
- [x] Check package against `REDCapR` sample databases
- [x] Check submission in [RHub](https://builder.r-hub.io/)
- [x] Code of conduct and contributing documentation

To properly address this we will need to determine how best to include/exclude API token calls for package examples and vignette rendering.

Other things to consider:

- ~[ ] Convert pipes from `%>%` to `|>`~
   - ~[ ] Remove any unnecessary `magrittr` `@import` calls~
- [x]  Rename internal `extract_repeat/nonrepeat_table` functions under `clean_*` to be less confusing with exported, outward-facing `extract_table/s` functions
   - Thesauraus options: `distill_*`, `derive_*`, `pull_*`
- [ ] Revisit `utils.R` to clean up, potentially move some out to separate files

### Checklist

- [x] The issue is atomic
- [x] The issue description is documented
- [x] The issue title describes the problem succinctly
- [x] Developers are assigned to the issue
- [x] Labels are assigned to the issue

**Comment by rsh52** [comment]
Updated checklist to reflect changes. NEWS section still to be made, vignettes/documentation to be reviewed.

Thoughts on the code of conduct @skadauke?

**Comment by skadauke** [comment]
@rsh52 - I made the README a whole bunch shorter and moved what was in it into a new "Getting Started" vignette which I also edited. Probably broke a bunch of stuff while doing so 🙈

Will plan to have a section added to explain how longitudinal projects work (probably not a full vignettes for 0.1) and the function documentation revised before we upload to CRAN Weds night.

Can we make the README the landing page of the pkgdown site? I'm not sure how to do this.

**Comment by rsh52** [comment]
@skadauke I think I've fixed the issues, all minor. The RMD index-entry names were duplicated and the GIF had to be copied over to the vignettes folder so the vignettes themselves could access it. I also had to update the Tidy Data URL from Haldey's HTML file to https://www.jstatsoft.org/article/view/v059i10. Not ideal, but the previous HTML page wouldn't pass the "canonical form" of the `urlchecker`. I also reverted the Hex image back to HTML from markdown, the markdown style doesn't render as well.

The README is basically now the landing page. Whatever vignette is named identically to the package name is what gets autopopulated into the landing, so as long as the README and `REDCapTidieR.Rmd` are identical then we're all good.
